package com.turling.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class QuestionTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuestionTypeAllPropertiesEquals(QuestionType expected, QuestionType actual) {
        assertQuestionTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertQuestionTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuestionTypeAllUpdatablePropertiesEquals(QuestionType expected, QuestionType actual) {
        assertQuestionTypeUpdatableFieldsEquals(expected, actual);
        assertQuestionTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuestionTypeAutoGeneratedPropertiesEquals(QuestionType expected, QuestionType actual) {
        assertThat(actual)
            .as("Verify QuestionType auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuestionTypeUpdatableFieldsEquals(QuestionType expected, QuestionType actual) {
        assertThat(actual)
            .as("Verify QuestionType relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuestionTypeUpdatableRelationshipsEquals(QuestionType expected, QuestionType actual) {
        // empty method
    }
}
