package com.turling.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class QuestionCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuestionCategoryAllPropertiesEquals(QuestionCategory expected, QuestionCategory actual) {
        assertQuestionCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertQuestionCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuestionCategoryAllUpdatablePropertiesEquals(QuestionCategory expected, QuestionCategory actual) {
        assertQuestionCategoryUpdatableFieldsEquals(expected, actual);
        assertQuestionCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuestionCategoryAutoGeneratedPropertiesEquals(QuestionCategory expected, QuestionCategory actual) {
        assertThat(actual)
            .as("Verify QuestionCategory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuestionCategoryUpdatableFieldsEquals(QuestionCategory expected, QuestionCategory actual) {
        assertThat(actual)
            .as("Verify QuestionCategory relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuestionCategoryUpdatableRelationshipsEquals(QuestionCategory expected, QuestionCategory actual) {
        // empty method
    }
}
